### ISSUE TITLE
Kubefirst should warn on new version

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#916] opened 2022-12-14 22:30 UTC
**What would you like to be added**:

When I run the `kubefirst` command, the CLI should warn me if there is a newer version available so I can upgrade as it may fix issues I have or add features that will make my life even better.

**Why is this needed**:

Maybe not needed at each run, and not sure the mechanism we want to use if we implement that, but it would need to check the actual version, the latest available, and if different, mention it to the user.

**Comment by johndietz** [comment] 2023-02-14 21:37
we should warn on the creation of mgmt clusters, otherwise we should allow them to stay pinned to the version of their mgmt cluster

**Comment by echoboomer** [comment] 2023-04-04 19:33
Closing. Duplicate of https://github.com/kubefirst/kubefirst/issues/546.

**Closed by echoboomer** 2023-04-04 19:33 UTC
Labels: feature
