### ISSUE TITLE
setup OIDC for local

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#1219] opened 2023-01-18 10:54 UTC
As a Kubefirst user, I want to use the same OIDC pattern I use for cloud in the local experience. So that I can login into Argo and Argo Workflow using SSO.

2. local needs the oidc provider
    - [https://github.com/kubefirst/gitops-template/blob/main/localhost/terraform/vault/oidc-scopes.tf](https://github.com/kubefirst/gitops-template/blob/main/localhost/terraform/vault/oidc-scopes.tf)
    - [https://github.com/kubefirst/gitops-template/blob/main/localhost/terraform/vault/oidc-provider.tf](https://github.com/kubefirst/gitops-template/blob/main/localhost/terraform/vault/oidc-provider.tf)
    - [https://github.com/kubefirst/gitops-template/blob/main/localhost/terraform/vault/oidc-clients.tf](https://github.com/kubefirst/gitops-template/blob/main/localhost/terraform/vault/oidc-clients.tf)
    - [https://github.com/kubefirst/gitops-template/blob/main/localhost/terraform/vault/oidc-groups.tf](https://github.com/kubefirst/gitops-template/blob/main/localhost/terraform/vault/oidc-groups.tf)

**It needs some exploration before creating the ACs.** The current state is: there is a OIDC provider setup (Vault), it's been called by Terraform, and maybe it's just missing to setup the applications to use the OIDC client for authentication.

**Comment by 6za** [comment] 2023-01-18 12:19
This ticket major AC are:
- [ ] Make `argo local`, be able to be logged with kbot credentials, similar to the one in the cloud version. (update terraform/argo yamls)
- [ ] Make `argocd local`, be able to be logged with kbot credentials, similar to the one in the cloud version. (update terraform/argo yamls)

**Comment by 6za** [comment] 2023-01-18 12:21
There is a possibility, that due to untrusted certificates the OIDC hand-shake may fail, explore how to workaround that.

**Comment by fharper** [comment] 2023-06-01 13:45
duplicate of #1534

**Closed by fharper** 2023-06-01 13:45 UTC
