### ISSUE TITLE
Ngrok + atlantis / GitHub webhook not responding

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#939] opened 2022-12-16 01:47 UTC
at current `main` branch, Ngrok URL is created and registered, but GitHub webhook fails to reach Ngrok address, making installation final Atlantis steps to fail.

p.s: it was working before, but was broke at some point.

**Comment by converge** [comment] 2022-12-16 16:53
@pagottoo have a look at this "Problems using Ngrok" session https://www.twilio.com/blog/using-ngrok-2022 , it might be the root cause of our issues. The explanation starts at "Another more serious problem is shown in the following screenshot."

**Comment by pagottoo** [comment] 2022-12-19 16:31
Moving to triage due to the impossibility of reproduction;

**Comment by converge** [comment] 2023-01-05 18:59
I could reproduce it with:

```
go run . local --metaphor-branch main
```

**Comment by converge** [comment] 2023-01-19 16:04
adding to 1.11.1 milestone since it's still happening for some people (it works most of the time, but not always).

**Comment by 6za** [comment] 2023-01-19 16:18
There is several discussion on this ticket and how hard it is to reproduce it, I would just clarify that I don't believe this issue should not block the next release, in case that still the case and we can provide evidence of its reproduction. 


It may be related to some flaky behavior of ngrok lib in use. To keep researching it is important, just to be careful to not hold next release due to the date commits, in particular to not block CIVO effort.

**Comment by marinhojess** [comment] 2023-01-19 17:11
Localhost nstallation completed successfully, even when not able to perform the atlantis plan and apply:

```
2023-01-19T14:04 INF ../../../../kubefirst/pkg/ngrok.go:50 > connection closed: <nil>
2023-01-19T14:04 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:04 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:04 INF ../../../../kubefirst/pkg/ngrok.go:50 > connection closed: <nil>
2023-01-19T14:04 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:04 INF ../../../../kubefirst/pkg/ngrok.go:50 > connection closed: <nil>
2023-01-19T14:04 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:04 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:05 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:05 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:05 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:05 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:05 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:05 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:06 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:06 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:06 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:06 INF ../../../../kubefirst/internal/githubWrapper/github.go:274 > waiting "atlantis plan" finish to proceed...
2023-01-19T14:06 INF ../../../../kubefirst/cmd/local/local.go:413 > unable to run "atlantis plan"
2023-01-19T14:06 INF ../../../../kubefirst/cmd/local/local.go:442 > sending mgmt cluster install completed metric
2023-01-19T14:06 INF ../../../../kubefirst/cmd/local/local.go:447 > Telemetry info sent
2023-01-19T14:06 INF ../../../../kubefirst/pkg/helpers.go:627 > Kubefirst installation finished successfully
2023-01-19T14:06 INF ../../../../kubefirst/cmd/local/postrun.go:23 > Starting the presentation of console and api for the handoff screen
2023-01-19T14:07 INF ../../../../kubefirst/pkg/helpers.go:676 > console UI is up and running
```

**Comment by marinhojess** [comment] 2023-01-19 17:14
Webhook returning status code 503 (service unavailable):

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/19623668/213513636-9d12af7d-2b81-44cf-adcf-5f3d59d1b8f6.png">

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/19623668/213513882-717d8b33-9e48-4691-b8cb-b0321af58870.png">

**Comment by marinhojess** [comment] 2023-01-19 17:29
Atlantis logs:

```
kubectl logs --since=24h atlantis-0 -n atlantis
{"level":"info","ts":"2023-01-19T17:01:25.449Z","caller":"server/server.go:795","msg":"Atlantis started - listening on port 4141","json":{}}
```

**Comment by 6za** [comment] 2023-01-19 17:37
This seems to be the log of the "phanton issue": `2023-01-19T14:04 INF ../../../../kubefirst/pkg/ngrok.go:50 > connection closed: <nil>`

**Comment by converge** [comment] 2023-01-19 19:24
when kubefirst / ngrok / atlantis 

**webhook response is NOT OK:**
```
curl https://< --- >.sa.ngrok.io/events
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta name="author" content="ngrok">
    <meta name="description" content="ngrok is the fastest way to put anything on the internet with a single command.">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link id="style" rel="stylesheet" href="https://cdn.ngrok.com/static/css/error.css">
    <noscript>Before you can serve HTML content, you must sign up for an ngrok account and install your authtoken. (ERR_NGROK_6022)</noscript>
    <script id="script" src="https://cdn.ngrok.com/static/js/error.js" type="text/javascript"></script>
  </head>
  <body id="ngrok">
    <div id="root" data-payload="< --- auth token here --- ></div>
  </body>
</html>
```

token payload:
```
{
  "authtokenURL": "https://dashboard.ngrok.com/get-started/your-authtoken",
  "cdnBase": "https://cdn.ngrok.com/",
  "code": "6022",
  "message": "Before you can serve HTML content, you must sign up for an ngrok account and install your authtoken.",
  "signupURL": "https://dashboard.ngrok.com/signup",
  "title": "Welcome to ngrok!"
}
```

**webhook response is OK**:

```
 ~  curl https://< --- >.sa.ngrok.io/events
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta name="author" content="ngrok">
    <meta name="description" content="ngrok is the fastest way to put anything on the internet with a single command.">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link id="style" rel="stylesheet" href="https://cdn.ngrok.com/static/css/error.css">
    <noscript>Tunnel < --- >.sa.ngrok.io not found (ERR_NGROK_3200)</noscript>
    <script id="script" src="https://cdn.ngrok.com/static/js/error.js" type="text/javascript"></script>
  </head>
  <body id="ngrok">
    <div id="root" data-payload="< --- auth token here ---> ="></div>
  </body>
</html>
```

token payload:
```
{
  "cdnBase": "https://cdn.ngrok.com/",
  "code": "3200",
  "message": "Tunnel 2cbd-191-248-106-91.sa.ngrok.io not found",
  "title": "Not Found"
}
```

**Comment by converge** [comment] 2023-01-19 20:06
**how I could reproduce it:**

1. have a open tunnel (using kubefirst local install / waiting at handoff screen)
2. destroy the current local install
3. run a new local install
4. ngrok will fail and return it[1]

[1]
```
{
  "authtokenURL": "https://dashboard.ngrok.com/get-started/your-authtoken",
  "cdnBase": "https://cdn.ngrok.com/",
  "code": "6022",
  "message": "Before you can serve HTML content, you must sign up for an ngrok account and install your authtoken.",
  "signupURL": "https://dashboard.ngrok.com/signup",
  "title": "Welcome to ngrok!"
}
```

**Closed** 2023-01-20 18:30 UTC
