### ISSUE TITLE
kubefirst local does not run on Ubuntu

### ISSUE THREAD

**Issue by jarededwards** [kubefirst/kubefirst#1347] opened 2023-03-10 15:29 UTC
a user had an error running `kubefirst local` on an ubuntu vm, this was replicated running an Ubunut image in civo
```
minio-769657f5c5-cm8gn        0/1     CrashLoopBackOff   34 (4m20s ago)   153m
minio-make-bucket-job-cb5r2   1/1     Running            3 (3m16s ago)    35m
minio-make-user-job-5rvbc     1/1     Running            3 (3m16s ago)    35m
```
logs from the minio pod
```
root@debug-1-4bf4-05c715:~# k -n minio logs pod/minio-769657f5c5-jjjsl
ERROR Unable to initialize backend: mkdir /export/.minio.sys: permission denied
```

**Comment by johndietz** [comment] 2023-03-10 20:09
quick update on this issue, we are able to replicate this community issue on civo ubuntu. we spent some time trying to find an easy "quick fix" that wouldn't require a release and haven't been able to identify one yet. we think that the issue has to do with the minio storage class and permissions of the minio volume mount that emulates s3 on the ubuntu host.
while we don't expect to have a fix today, we are going to try to get a permanent fix included in the 2.0 release to support the user who identified this condition if we're able to remedy by wednesday of next week.

**Comment by jizusun** [comment] 2023-03-20 14:19
Oh my final hack is, 

after running `kubefirst local`, I watch the folder `$HOME/.k1`, and once `minio-storage` is created, I run 
```sh
chmod -R 777 minio-storage
```

**Comment by johndietz** [comment] 2023-04-24 14:07
hello @jizusun - wanted to thank you for this input. with our 2.0 release out the door and a few high-priority patches, we've just circled back to this and confirmed that we are indeed operational on ubuntu without any os volume hackery.

wanted to share with you the startup script that we used to test in case it's helpful to you, this was tested on a civo xl compute vm running Ubuntu 22.04.

### startup script to install docker, ca bundle, kubectl, mkcert, kubefirst, and add github/gitlab to known_hosts
```
#!/bin/bash
sudo apt-get update
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    wget \
    libnss3-tools \
    --yes
sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin --yes
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
mv kubectl /usr/local/bin/
chmod +x /usr/local/bin/kubectl
apt-get install wget libnss3-tools
wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64
mv mkcert-v1.4.4-linux-amd64 /usr/bin/mkcert
chmod +x /usr/bin/mkcert
mkcert -install
kubectl version
export KUBEFIRST_VERSION=`curl https://github.com/kubefirst/kubefirst/releases/latest  -Ls -o /dev/null -w %%{url_effective} | grep -oE "[^/]+$"`
curl -s -LO "https://github.com/kubefirst/kubefirst/releases/download/$${KUBEFIRST_VERSION}/kubefirst_$${KUBEFIRST_VERSION:1}_linux_amd64.tar.gz"
tar -xvf kubefirst_$${KUBEFIRST_VERSION:1}_linux_amd64.tar.gz -C /usr/local/bin/
chmod +x /usr/local/bin/kubefirst
ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
ssh-keyscan github.com >> ~/.ssh/known_hosts
kubefirst version
```

### on the host, run the following to add local ca to cert store and run kubefirst k3d create
(be sure to export your GITHUB_TOKEN / GITLAB_TOKEN)
```
mkcert -install
export GITHUB_TOKEN=ghp_XXXXXXXXXXXXXXXXXXXXXX
kubefirst k3d create
```

thanks for this report and for your patience while we got 2.0 out the door. please let us know if you have any other needs from kubefirst on ubuntu vm support.

**Comment by fharper** [comment] 2023-09-20 18:22
@jizusun closing this issue since it was fixed in 2.0, but let us know if you still can't use kubefirst on Ubuntu.

@johndietz is there anything to add to the installation documentation that is specific to Ubuntu that could help future users?

**Closed by fharper** 2023-09-20 18:22 UTC
Labels: bug, community

**Comment by Brother-Blue** [comment] 2023-10-16 14:58
I'm running into this on Ubuntu 22.04 after installing it as per [the documentation](https://github.com/kubefirst/kubefirst/blob/main/build/README.md). 

```sh
$ kubefirst k3d create
------------------------------------------------
Follow your logs in a new terminal with: 
   tail -f -n +1 /home/test/.k1/logs/log_1697467691.log 
------------------------------------------------
Error: known_hosts file does not exist - please run `ssh-keyscan github.com >> ~/.ssh/known_hosts` to remedy

If a detailed error message was available, please make the necessary corrections before retrying.
You can re-run the last command to try the operation again.
```

Following the logs doesn't show any additional information.

I also tried installing it via the script @johndietz provided but getting the same results.

**Comment by fharper** [comment] 2023-10-16 15:46
@Brother-Blue : did you run the proposed command `ssh-keyscan github.com >> ~/.ssh/known_hosts` as suggested by the CLI output? It should solve the issue.

**Comment by Brother-Blue** [comment] 2023-10-16 15:50
I did but it made no difference. Nothing showed in the logs and the same error message came up after retrying the create command.

**Comment by fharper** [comment] 2023-11-16 22:02
@Brother-Blue if you still have this issue, join our [Slack community](https://kubefirst.io/slack) and we will help you about it, as it's a different problem than this initial issue.

**Comment by Brother-Blue** [comment] 2023-11-17 10:16
Thank you @fharper I put the project on the back burner for now but I'll join the slack if I run into the same issue in the future.
