### ISSUE TITLE
Init: Issue when creating buckets

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#402] opened 2022-09-15 16:05 UTC
# Overview

We have an issue on to tag buckets on east-1 aws region. 

```bash 
LOG: 2022/09/14 20:54:46.923253 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:113: [DEBUG] S3 put bucket versioning: &s3.PutBucketVersioningInput{Bucket:(*string)(0x14000828690), VersioningConfiguration:(*types.VersioningConfiguration)(0x140007925d0), ChecksumAlgorithm:"", ContentMD5:(*string)(nil), ExpectedBucketOwner:(*string)(nil), MFA:(*string)(nil), noSmithyDocumentSerde:document.NoSerde{}}
LOG: 2022/09/14 20:54:47.322916 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:507: tagging bucket... k1-gitlab-backup-example:kubernickels
LOG: 2022/09/14 20:54:47.323016 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:536: operation error S3: PutBucketTagging, failed to resolve service endpoint, an AWS region is required, but was not found
LOG: 2022/09/14 20:54:47.341939 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:128: bucket k1-gitlab-backup-example exists
LOG: 2022/09/14 20:54:47.342044 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:81: creating chartmuseum bucket k1-chartmuseum-example
LOG: 2022/09/14 20:54:47.342056 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:84: region is  us-west-1
LOG: 2022/09/14 20:54:48.222853 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:113: [DEBUG] S3 put bucket versioning: &s3.PutBucketVersioningInput{Bucket:(*string)(0x14000829ab0), VersioningConfiguration:(*types.VersioningConfiguration)(0x1400052e6f0), ChecksumAlgorithm:"", ContentMD5:(*string)(nil), ExpectedBucketOwner:(*string)(nil), MFA:(*string)(nil), noSmithyDocumentSerde:document.NoSerde{}}
LOG: 2022/09/14 20:54:48.507543 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:507: tagging bucket... k1-chartmuseum-example:kubernickels
LOG: 2022/09/14 20:54:48.507689 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:536: operation error S3: PutBucketTagging, failed to resolve service endpoint, an AWS region is required, but was not found
LOG: 2022/09/14 20:54:48.527312 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:128: bucket k1-chartmuseum-example exists
LOG: 2022/09/14 20:54:49.528587 /Users/jared/git/kubefirst/github/kubefirst/cmd/init.go:172: BucketRand() complete
```

**Comment by 6za** [comment] 2022-09-16 11:46
To ensure, virginia region particularities are accounted for, ensure you test into at least 2 regions: 
- virginia region
- and non-virginia region

**Comment by converge** [comment] 2022-09-16 15:53
note; log is using us-west-1

I tried to reproduce the bug in different way, but wasn't able to.

Attempts to reproduce the bug:
```
# go run . clean --destroy-buckets --destroy-confirm
# go run . init --admin-email user@email.com --cloud aws --hosted-zone-name user.domain --region us-west-1  --cluster-name user_domain --profile default --aws-nodes-spot --gitops-branch main

# go run . clean --destroy-buckets --destroy-confirm
# go run . init --admin-email user@email.com --cloud aws --hosted-zone-name user.domain --region us-east-1   --cluster-name user_domain --profile default --aws-nodes-spot --gitops-branch main

# go run . clean --destroy-buckets --destroy-confirm
# go run . init --admin-email user@email.com --cloud aws --hosted-zone-name user.domain --region eu-central-1   --cluster-name user_domain --profile default --aws-nodes-spot --gitops-branch main
```

I also tried:
1. go run . clean <args>
2. go run . init <args>
3. go run . init <args> # force second run

I'm closing the ticket since I wasn't able to reproduce it. I'll be more than happy to try it again if we can have a way to reproduce it, and re-open the ticket.

**Comment by 6za** [comment] 2022-09-16 16:35
Did you check the logs?
the buckets are created but they produce the error on the logs when trying to activate the versioning.

**Comment by 6za** [comment] 2022-09-16 16:36
From my morning install of this morning: (logs form init)
```
LOG: 2022/09/16 10:57:42.696134 /home/developer/app/internal/aws/aws.go:113: [DEBUG] S3 put bucket versioning: &s3.PutBucketVersioningInput{Bucket:(*string)(0xc00079d940), VersioningConfiguration:(*types.VersioningConfiguration)(0xc00029b170), ChecksumAlgorithm:"", ContentMD5:(*string)(nil), ExpectedBucketOwner:(*string)(nil), MFA:(*string)(nil), noSmithyDocumentSerde:document.NoSerde{}}
LOG: 2022/09/16 10:57:43.182086 /home/developer/app/internal/aws/aws.go:507: tagging bucket... k1-state-store-6zray-kubefast-com-gh:6zray_kubefast_com
LOG: 2022/09/16 10:57:43.182740 /home/developer/app/internal/aws/aws.go:536: operation error S3: PutBucketTagging, failed to resolve service endpoint, an AWS region is required, but was not found
LOG: 2022/09/16 10:57:43.187930 /home/developer/app/internal/aws/aws.go:128: bucket k1-state-store-6zray-kubefast-com-gh exists
LOG: 2022/09/16 10:57:43.188639 /home/developer/app/internal/aws/aws.go:81: creating argo-artifacts bucket k1-argo-artifacts-6zray-kubefast-com-gh
LOG: 2022/09/16 10:57:43.189153 /home/developer/app/internal/aws/aws.go:84: region is  us-west-1
LOG: 2022/09/16 10:57:44.986002 /home/developer/app/internal/aws/aws.go:113: [DEBUG] S3 put bucket versioning: &s3.PutBucketVersioningInput{Bucket:(*string)(0xc000206a00), VersioningConfiguration:(*types.VersioningConfiguration)(0xc0001342a0), ChecksumAlgorithm:"", ContentMD5:(*string)(nil), ExpectedBucketOwner:(*string)(nil), MFA:(*string)(nil), noSmithyDocumentSerde:document.NoSerde{}}
LOG: 2022/09/16 10:57:45.489970 /home/developer/app/internal/aws/aws.go:507: tagging bucket... k1-argo-artifacts-6zray-kubefast-com-gh:6zray_kubefast_com
LOG: 2022/09/16 10:57:45.490855 /home/developer/app/internal/aws/aws.go:536: operation error S3: PutBucketTagging, failed to resolve service endpoint, an AWS region is required, but was not found
LOG: 2022/09/16 10:57:45.495249 /home/developer/app/internal/aws/aws.go:128: bucket k1-argo-artifacts-6zray-kubefast-com-gh exists
LOG: 2022/09/16 10:57:45.495588 /home/developer/app/internal/aws/aws.go:81: creating gitlab-backup bucket k1-gitlab-backup-6zray-kubefast-com-gh
LOG: 2022/09/16 10:57:45.495958 /home/developer/app/internal/aws/aws.go:84: region is  us-west-1
LOG: 2022/09/16 10:57:47.115996 /home/developer/app/internal/aws/aws.go:113: [DEBUG] S3 put bucket versioning: &s3.PutBucketVersioningInput{Bucket:(*string)(0xc0006e4350), VersioningConfiguration:(*types.VersioningConfiguration)(0xc0000ad3b0), ChecksumAlgorithm:"", ContentMD5:(*string)(nil), ExpectedBucketOwner:(*string)(nil), MFA:(*string)(nil), noSmithyDocumentSerde:document.NoSerde{}}
LOG: 2022/09/16 10:57:47.590731 /home/developer/app/internal/aws/aws.go:507: tagging bucket... k1-gitlab-backup-6zray-kubefast-com-gh:6zray_kubefast_com
LOG: 2022/09/16 10:57:47.591462 /home/developer/app/internal/aws/aws.go:536: operation error S3: PutBucketTagging, failed to resolve service endpoint, an AWS region is required, but was not found
LOG: 2022/09/16 10:57:47.594738 /home/developer/app/internal/aws/aws.go:128: bucket k1-gitlab-backup-6zray-kubefast-com-gh exists
LOG: 2022/09/16 10:57:47.595084 /home/developer/app/internal/aws/aws.go:81: creating chartmuseum bucket k1-chartmuseum-6zray-kubefast-com-gh
LOG: 2022/09/16 10:57:47.595448 /home/developer/app/internal/aws/aws.go:84: region is  us-west-1
LOG: 2022/09/16 10:57:49.262661 /home/developer/app/internal/aws/aws.go:113: [DEBUG] S3 put bucket versioning: &s3.PutBucketVersioningInput{Bucket:(*string)(0xc000492ce0), VersioningConfiguration:(*types.VersioningConfiguration)(0xc0005baf90), ChecksumAlgorithm:"", ContentMD5:(*string)(nil), ExpectedBucketOwner:(*string)(nil), MFA:(*string)(nil), noSmithyDocumentSerde:document.NoSerde{}}
LOG: 2022/09/16 10:57:49.757123 /home/developer/app/internal/aws/aws.go:507: tagging bucket... k1-chartmuseum-6zray-kubefast-com-gh:6zray_kubefast_com
LOG: 2022/09/16 10:57:49.758574 /home/developer/app/internal/aws/aws.go:536: operation error S3: PutBucketTagging, failed to resolve service endpoint, an AWS region is required, but was not found
LOG: 2022/09/16 10:57:49.762536 /home/developer/app/internal/aws/aws.go:128: bucket k1-chartmuseum-6zray-kubefast-com-gh exists
```

**Comment by converge** [comment] 2022-09-16 16:46
> 

I did, no errors (except when I called `go run . init <args>` twice without clean.

Can I use your command line calls to reproduce the issues (slack)?

**Comment by converge** [comment] 2022-09-16 16:46
> Did you check the logs?
> the buckets are created but they produce the error on the logs when trying to activate the versioning.

I did, no errors (except when I called go run . init <args> twice without clean.

Can I use your command line calls to reproduce the issues (slack)?

**Comment by converge** [comment] 2022-09-16 18:50
For some reason I didn't have the time to look into was that it was failing for GitHub only.

**Closed** 2022-09-16 19:13 UTC
Labels: bug
