### ISSUE TITLE
kubefirst local docs needed

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#751] opened 2022-11-16 21:53 UTC
we need kubefirst local docs
- [skipped] system requirements
depends on https://github.com/kubefirst/kubefirst/issues/753, docs requirement called out that item
[x] how to install
https://docs.kubefirst.io/preprod/kubefirst/local/install.html
[x] creating your first automated terraform pull request
https://docs.kubefirst.io/preprod/kubefirst/local/after-install.html#step-2-make-your-first-automated-terraform-change
- onboarding a new admin onto kubefirst local
[skipped] introduce new admin when implementing oidc to local
- how to deploy metaphor (or the metaphor suite until metaphor-slim is ready)
[x] https://docs.kubefirst.io/preprod/kubefirst/local/after-install.html#step-3-deliver-metaphor-to-development-staging-and-production
- differences between kubefirst local and kubefirst cloud
[incomplete]
- troubleshooting
[not good enough yet]
- how to reconnect
[not yet]
- how to destroy
https://docs.kubefirst.io/preprod/kubefirst/local/destroy.html

**Comment by johndietz** [comment] 2022-11-16 21:53
after first cut, individual tickets for anything that remains for team to pick up and run with

**Comment by 6za** [comment] 2022-12-15 12:21
Things to be documented on 1.11:
- There is a new flow of create/destroy for local that is not shared with cloud. 
```bash 
kubefirst local
kubefirst local destroy 
```
Double check with @converge  for details. 

- `Mkcerts` need to be installed so certs are valid automatically 
> check details with @pagottoo / @converge 

- Ngrok for atlantis only works for the time the installer is showing the hand-off screen, after that atlantis will not get signals from github and not work as expected. this pipe can't be recovered after the screen is closed or the tunnel times-out.

- known dependencies: docker, minimal machine size for docker settings...
- There known limitations of using it from a 5G or bad internet connection.
- It would be nice to have some mention that load balancer on cloud installs may hang and not be deleted, making destroy to fail. Guide user for workaround.
- Do we need to promote mode in the docs Graviton?
- We upgraded k8s on AWS, we may need to update some pages and promote that information.

**Comment by 6za** [comment] 2022-12-15 12:22
- maybe to promote that CI tools were shrunk(kubefirst build image)

**Comment by 6za** [comment] 2022-12-15 13:06
- to cover how admins/users can change their passwords on the new stack. 
Details(gif): https://github.com/kubefirst/kubefirst/issues/748#issuecomment-1332101262

**Comment by 6za** [comment] 2022-12-15 13:08
Questions that may appear: 
- Can I keep using local, after I exit the handoff screen?
- What can I do with the local kubefirst?
- Exploring the cloud: Atlantis To add User, Exploring CI of metaphor-X, exploring gitops(how to add an app).

**Comment by fharper** [comment] 2022-12-16 21:41
**I suggest we create an issue for each section to modify, page to create, or group of information to add, in separate issues, so it's easier to track, follow-up, and discuss. It doesn't take much more time to do it like that when done from the beginning :) **

I created issues for the many different things written in this thread. Let me know if I forgot something or if I wrote something incorrect please.

> differences between kubefirst local and kubefirst cloud incomplete
Created #946 

> troubleshooting not good enough yet
Created #947

> Can I keep using local, after I exit the handoff screen?
added to #947

> What can I do with the local kubefirst?
added in #946

> Atlantis To add User
Created #949, but not specific to `local`

> exploring gitops(how to add an app)
Created #948, but not specific to `local`

> to cover how admins/users can change their passwords on the new stack.
Created #950, but not specific to `local`

> There is a new flow of create/destroy for local that is not shared with cloud.
@johndietz updated the documentation with that information, unless there is more to write about?

> known dependencies: docker, minimal machine size for docker settings...
Created #951 but it needs attention.

> There known limitations of using it from a 5G or bad internet connection.
Created #952, but would like anyone to chime in with more limitations, if any, and more details on the internet connection limitations.

> It would be nice to have some mention that load balancer on cloud installs may hang and not be deleted, making destroy to fail. Guide user for workaround.
Added to #947

Questions:
- what does "how to reconnect" mean? What are we reconnecting to? @johndietz 
- what is the CI of metaphor-X? @6za 
- Can you explain to me what is the CI tools were shrunk(kubefirst build image)? @6za 
- Mkcerts need to be installed so certs are valid automatically, is it the case @converge ? I didn't have it installed on my computer, but I think everything was working correctly.
- Ngrok for atlantis only works for the time the installer is showing the hand-off screen, after that atlantis will not get signals from github and not work as expected. this pipe can't be recovered after the screen is closed or the tunnel times-out. Is it right @pagottoo / @converge?
- Do we need to promote mode in the docs Graviton? Good question, @johndietz was working on the support, not sure if it's finalized.
- We upgraded k8s on AWS, we may need to update some pages and promote that information. Can the person who have that knowledge create the proper issues please?

Please comment in the proper issue for the ones created :)

and thanks for all the inputs @6za !

**Comment by 6za** [comment] 2022-12-19 12:05
@fharper Some answers: 
1 - what does "how to reconnect" mean? What are we reconnecting to? @johndietz
> it seems to refer to `ngrok` webhook, as we need an ngrok tunnel to allow github to reach a local installation of kubefirst. This approach has some limitations:
> 1 - The tunnel is only open while the installer of the first install is still open and showing the handoof screen 
> 2 - There is max window this tunnel is open, after that window of time expires ngrok close it.
> 3 - Up to know there is no way to "Re-connect" recreate the tunnel and update github webhook for atlantis.

**Comment by 6za** [comment] 2022-12-19 12:07
2 - what is the CI of metaphor-X?
> Local/Cloud install one or multiple metaphor applications after the cluster is ready. Metaphor-X refers to the metaphor bundle to a given flavor. I believe for local is metaphor-slim and for cloud is metaphor, metaphor-go and metaphor-frontend.

**Comment by 6za** [comment] 2022-12-19 12:09
3 - Can you explain to me what is the CI tools were shrunk(kubefirst build image)?
> It seems we retired [chubbo](https://hub.docker.com/r/kubefirst/chubbo) 🐕  image, and adopted a smaller one for local and cloud, to make CI building faster. The CI that build and installs metaphor applications to the cluster.

**Comment by fharper** [comment] 2022-12-19 17:37
Based on @6za comments, I also created #955 

@6za: can you create a documentation issue for each of the question you answered (2 & 3) please as I'm not quite sure what you want us to add to the documentation, sorry 😅 We can discuss more in their own issues to make it easier.

**Comment by fharper** [comment] 2022-12-19 21:30
> Mkcerts need to be installed so certs are valid automatically.

I don't think it's valid anymore as it's accessible from `~/.k1/tools/mkcert`. Let me know if I'm wrong.

**Comment by fharper** [comment] 2022-12-19 21:31
> Do we need to promote mode in the docs Graviton?

Good question, @johndietz was working on the support, not sure if it's finalized. John?

**Comment by fharper** [comment] 2022-12-19 21:32
> We upgraded K8s on AWS, we may need to update some pages and promote that information.

Can the person who have that knowledge create the proper issue please?

**Comment by fharper** [comment] 2022-12-19 21:33
Closing this issue as I created the individual issues for better tracking, and history. I also created a milestone for 1.11 documentations, and will add those in it.

Feel free to comment on the remaining two questions in this thread even if the issue is closed.

**Closed by fharper** 2022-12-19 21:33 UTC
Labels: needs docs, aws, local
