### ISSUE TITLE
Getting error when installing kubefirst on WSL-2

### ISSUE THREAD

**Issue by mwoodpatrick** [kubefirst/kubefirst#2173] opened 2024-05-05 23:02 UTC
### Which version of kubefirst are you using?

v2.4.6

### Which cloud provider?

k3d (local)

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

Linux

### What is the issue?

When running:

`kubefirst k3d create`

I'm getting an error at the end of the installation (after Configuring Vault completed ok) I get:

`Error: exit status 1`

Any suggestions as to what the error is or how to debug, the log shows:

{"level":"info","time":"2024-05-05T15:11:55-07:00","message":" export AWS_ACCESS_KEY_ID = *****"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m╷\u001b[0m\u001b[0m"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mUnsupported attribute\u001b[0m"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m  on oidc-clients.tf line 43, in module \"gitlab\":"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m  43:   secret_mount_path = vault_mount.secret\u001b[4m.pat\u001b[0m\u001b[0m"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mThis object has no argument, nested block, or exported attribute named"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\"pat\". Did you mean \"path\"?"}
{"level":"warn","time":"2024-05-05T15:11:57-07:00","message":"ERR: \u001b[31m╵\u001b[0m\u001b[0m"}
{"level":"error","error":"exit status 1","time":"2024-05-05T15:11:57-07:00","message":"command \"/home/mwoodpatrick/.k1/kubefirst/tools/terraform\" failed"}
{"level":"debug","time":"2024-05-05T15:11:57-07:00","message":"error: terraform apply -auto-approve for /home/mwoodpatrick/.k1/kubefirst/gitops/terraform/vault failed exit status 1"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment] 2024-05-06 13:04
@mwoodpatrick: thanks for reporting, I'll try to replicate the issue and keep you in the loop.

**Comment by fharper** [comment] 2024-05-13 13:40
@mwoodpatrick: sorry for the delay, testing it now. Just to be sure, the report mentions GitHub, but the error has GitLab written in it. I will test both, but I want to be sure of what you tried when you get this error.

**Comment by mwoodpatrick** [comment] 2024-05-13 16:23
I am using GitHub, any suggestions on the best way for me to debug this further so I can get some insight on where the error is happening?

**Comment by fharper** [comment] 2024-05-13 16:57
Does this error happen again if you retry the same command?

If so, can you show me the output of `kubectl get pods -A` please.

**Comment by mwoodpatrick** [comment] 2024-05-13 20:43
So I did a clean install with 2.4.8 and this time I got the error:

Error: unable to reach vault over https - this is likely due to the mkcert certificate store missing. please install it via `/home/mwoodpatrick/.k1/kubefirst/tools/mkcert -install`

Is this expected?

Also this using this version I'm still seeing the other issue I reported a day or so ago:

Running kubefirst changes my stty settings #2176

**Comment by fharper** [comment] 2024-05-16 16:31
> Is this expected?

Yes, you need to install this. You can find more information about this needed installation step at https://docs.kubefirst.io/k3d/quick-start/install#install-the-ca-certificate-authority-of-mkcert-in-your-trusted-store

> lso using this using this version I'm still seeing the other issue I reported a day or so ago

It make sense as we didn't tackle this bug yet, but the team has been notified and I was able to reproduce.

**Comment by mwoodpatrick** [comment] 2024-05-18 13:38
I'm running on "Debian GNU/Linux 12 (bookworm)" so I don't have brew but installed mkcert using:

```
sudo apt install mkcert libnss3-tools
mkcert -install
```
Including the additional steps for [Windows with WSL](https://docs.kubefirst.io/k3d/quick-start/install/#additional-steps-for-windows-with-wsl)

This was completed without issue and I was able to get further running:

`kubefirst k3d create`

This did install the k3d clusters and argo but did hit some issues see [log](https://drive.google.com/file/d/1IWpYAkshcKEfEa7v0nOOig4WVmAzmxU4/view?usp=drive_link)

**Comment by fharper** [comment] 2024-05-21 12:49
It is supposed to detect it, and still working on macOS. Let me try on WSL2 with Debian.

**Comment by fharper** [comment] 2024-05-21 14:48
I tried on Debian, and it is showing the following screen when I didn't have the environment variable set.

![image](https://github.com/kubefirst/kubefirst/assets/1170989/a47738a4-2495-4b61-8975-5bdfcdca5196)

So since you were able to crate a cluster properly, and I cannot reproduce the token one, I'll close this issue.

If you encounter the same issue about the token in the future, create a new issue so it will be easier to follow as this one was about multiple things.

**Closed by fharper** 2024-05-21 14:48 UTC
Labels: bug
