### ISSUE TITLE
Make metaphor optional for console

### ISSUE THREAD

**Issue by CristhianF7** [kubefirst/kubefirst#521] opened 2022-10-06 18:13 UTC
A new flag was added to the CLI and the console is expecting metaphor to be working. 

Add a new flag to the internal API: "option.metaphor.skip"
Use the new flag in the Console to hide/show the cards

**Comment by fharper** [comment] 2023-09-20 19:55
Adding this would help add this feature request https://github.com/kubefirst/kubefirst/issues/1716

**Comment by fharper** [comment] 2023-09-21 17:18
Duplicate of #1716 since the new issue englob not just the API, but also the CLI, and UI experience. Even if now we do not install metaphor on the management cluster anymore (we do on the workload ones), it's still a feature that would be interesting for our users.

**Closed by fharper** 2023-09-21 17:18 UTC
Labels: feature, duplicate
