### ISSUE TITLE
Some `kubefirst` CLI commands hangs after execution

### ISSUE THREAD

**Issue by alebcay** [kubefirst/kubefirst#1902] opened 2023-11-07 15:47 UTC
### Which version of kubefirst are you using?

2.3.5

### Which cloud provider?

None specific

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

None specific

### Which Operating System?

macOS

### What is the issue?

Running some `kubefirst` commands hangs after the command executes, even commands that one would not expect them to hang, such as `kubefirst completion` or `kubefirst help`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment] 2023-11-08 02:21
thanks for reporting, it's a duplicate of #1883

**Closed by fharper** 2023-11-08 02:21 UTC
Labels: bug
