### ISSUE TITLE
Bug: Wrong Version installation of Kubefirst via brew

### ISSUE THREAD

**Issue by PatrickLaabs** [kubefirst/kubefirst#1555] opened 2023-05-20 18:53 UTC
### Which version of kubefirst are you using?

v2.0.8

### Which installation type?

k3d (local)

### Which distributed Git provider?

GitHub

### What is the issue?

On a fresh Ubuntu Jammy server with homebrew installed, I run into the issue, that installing kubefirst via brew returns a false Version.
On my macOS Ventura (also installed via brew) the version is just fine.

Snippet from Ubuntu:
``` sh
kubefirst version

kubefirst-cli golang utility version: 2.0.8
```

Snippet from macOS:
``` sh
kubefirst version

kubefirst-cli golang utility version: v2.0.8
```

Running a kubefirst create with the 2.0.8 version returns some kind of a misleading error message:
``` sh
Running preflight checks                ... done! [5 in 7.211s]
Cloning and formatting git repositories ...  0.0% [......................................] [0 in 89.989ms]
[###########################################.............................................] [7s]
Error: lstat /home/patrick/.k1/gitops/k3d-github/: no such file or directory
```

One user also reported some kind of this error, so I am not sure, if this might be a duplicat (I was not able to find an issue regarding this kind of error/bug)
[Link to Slack](https://kubefirst.slack.com/archives/C03U34WJ7FW/p1682518622834089)

Edit:
The Installation on a RaspberryPi via brew was just fine.
``` sh
kubefirst version

kubefirst-cli golang utility version: v2.0.8

➜  ~ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PatrickLaabs** [comment] 2023-05-20 19:04
I guess I found something:

Looking up for kubefirst at brew.sh you get these Installation instructions, which differ from those from the documentation:

[Brew.sh Installation Instructions](https://formulae.brew.sh/formula/kubefirst#default)

[Official Documentation](https://docs.kubefirst.io/kubefirst/overview#install-the-kubefirst-cli)

Following the documentation works well, as intended and returns the correct version for kubefrist.
``` sh
 kubefirst version

kubefirst-cli golang utility version: v2.0.8
```

I guess it could be nice, if the given instructions from brew.sh is the same as kubefirst official documentation.

**Comment by fharper** [comment] 2023-05-23 21:10
Unfortunately, we do not manage the formula in the official Homebrew repository, hence why we ask our users to tap into our own repository before installing.

I'll check with the team if we can take the ownership of it.

**Comment by fharper** [comment] 2023-06-12 19:56
Since the issue isn't with the CLI, but as you noted, the two different formula, I [created an issue](https://github.com/kubefirst/kubefirst/issues/1606) about doing something specific about that, so I'm closing this one. Thanks again for reporting, hopefully, we'll fix that problem sooner than later.

**Closed by fharper** 2023-06-12 19:56 UTC
Labels: bug
